Removed heap allocation of AsyncAdapter R/W handlers (fix: #146)
talostrading/sonic pull request #151
Opened 2024-12-12 00:49 UTC by MaxMaeder

Implemented read/write handlers in `AsyncAdapter` using the Reactor pattern (following from a18cfe8 and 08d3705), replacing `getReadHandler` and `getWriteHandler` which allocated the handler closure on the heap.

Sorry this took a bit longer than I estimated–I've been prepping for the Talos interview process (I have my final one tomorrow, wish me luck!)

2024-12-12 12:11 UTC, sergiu128 commented on async_adapter.go
> +func (a *AsyncAdapter) scheduleRead(b []byte, readBytes int, cb AsyncCallback) {
We can get rid of the `b []byte` param here, it's not used

2024-12-12 12:11 UTC, sergiu128 commented on async_adapter.go
> +func (a *AsyncAdapter) scheduleWrite(b []byte, writtenBytes int, cb AsyncCallback) {
We can get rid of the `b []byte` param here, it's not used

2024-12-12 12:12 UTC, sergiu128 commented on async_adapter.go
>  func (a *AsyncAdapter) asyncWriteNow(b []byte, writtenBytes int, writeAll bool, cb AsyncCallback) {
nitpick: let's get the naming in line with file.go. `writtenBytes -> wroteSoFar` and `readBytes -> readSoFar`.

2024-12-12 12:13 UTC, sergiu128 requested changes
Looks good and change is correct! Just a few notes, then I will merge. Thank you very much!

If anything is unclear about the code or you have more questions then feel free to reach out at sergiu@tungsten.computer.

2024-12-12 15:18 UTC, MaxMaeder commented
I've made the requested changes!

Issue #150 looks interesting, I enjoy working on low-level communication and memory management stuff. I have finals coming up for school, so I probably won't get to it for at least a week.

2024-12-13 03:31 UTC, sergiu128 approved these changes

2024-12-13 03:31 UTC, merged